### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by yanhonglin** [JuQiang/wxUnpacker#1]
Traceback (most recent call last):
  File "D:\Python\wxUnpacker-main\wxUnpacker-main\wx.py", line 490, in <module>
    main()
  File "D:\Python\wxUnpacker-main\wxUnpacker-main\wx.py", line 463, in main
    process_package(buf)
  File "D:\Python\wxUnpacker-main\wxUnpacker-main\wx.py", line 141, in process_package
    write_file(fname, content, "w")
  File "D:\Python\wxUnpacker-main\wxUnpacker-main\wx.py", line 88, in write_file
    f.write(buf)
UnicodeEncodeError: 'gbk' codec can't encode character '\xa5' in position 147280: illegal multibyte sequence

win11 python3.9 运行报错 请问这个怎么解决啊，能否加个联系方式

**Comment by TsingShui** [comment]
windows 下是会有问题，mac下畅通无阻

**Comment by yanhonglin** [comment]
大佬 知道怎么解决吗

**Comment by TsingShui** [comment]
这个拆包目前也有点问题，修了也没啥用。

**Comment by yad1d1** [comment]
检查下代码中的open方法，如果是"r"和"w"模式，加个编码encoding="utf-8"即可解决
